// Code generated by running "go generate" in golang.org/x/text. DO NOT EDIT.

package i18n

import (
	"golang.org/x/text/language"
	"golang.org/x/text/message"
	"golang.org/x/text/message/catalog"
)

type dictionary struct {
	index []uint32
	data  string
}

func (d *dictionary) Lookup(key string) (data string, ok bool) {
	p, ok := messageKeyToIndex[key]
	if !ok {
		return "", false
	}
	start, end := d.index[p], d.index[p+1]
	if start == end {
		return "", false
	}
	return d.data[start:end], true
}

func init() {
	dict := map[string]catalog.Dictionary{
		"en_US": &dictionary{index: en_USIndex, data: en_USData},
		"zh_CN": &dictionary{index: zh_CNIndex, data: zh_CNData},
		"zh_TW": &dictionary{index: zh_TWIndex, data: zh_TWData},
	}
	fallback := language.MustParse("en-US")
	cat, err := catalog.NewFromMap(dict, catalog.Fallback(fallback))
	if err != nil {
		panic(err)
	}
	message.DefaultCatalog = cat
}

var messageKeyToIndex = map[string]int{
	"* Leave blank to record no log and delete the original log file.": 69,
	"* Refer to the [common] section of the FRP configuration file.":   116,
	"* Refer to the parameters supported by FRP.":                      162,
	"* Support batch import, one link per line.":                       215,
	"A selection is required.":                                         230,
	"About":                                                            15,
	"Absolute":                                                         81,
	"Add":                                                              179,
	"Admin":                                                            74,
	"Admin Address":                                                    75,
	"Admin Port":                                                       76,
	"Advanced":                                                         107,
	"All":                                                              34,
	"All Files":                                                        3,
	"An error occurred while checking for a software update.": 21,
	"Another config already exists with the name \"%s\".":     46,
	"Are you sure you would like to delete config \"%s\"?":    49,
	"Are you sure you would like to delete proxy \"%s\"?":     209,
	"Are you sure you would like to disable proxy \"%s\"?":    211,
	"Assets":                 78,
	"Audience":               62,
	"Auth":                   57,
	"Auth Method":            58,
	"Authentication":         65,
	"Auto Delete":            80,
	"Bandwidth":              139,
	"Basic":                  52,
	"Bind Address":           129,
	"Bind Port":              130,
	"Built on: %s":           2,
	"Cancel":                 24,
	"Certificate":            101,
	"Certificate Files":      5,
	"Certificate Key":        103,
	"Change Password":        186,
	"Check Interval":         161,
	"Check Timeout":          159,
	"Check Type":             158,
	"Check for updates":      18,
	"Checking for updates":   17,
	"Client":                 137,
	"Common Only":            35,
	"Compression":            143,
	"Config already exists":  117,
	"Config already removed": 28,
	"Configuration":          25,
	"Configuration Files":    4,
	"Connection":             86,
	"Copy":                   174,
	"Copy Access Address":    207,
	"Copy Share Link":        39,
	"Create a Copy":          33,
	"Custom":                 114,
	"Custom Domains":         133,
	"Custom Options":         115,
	"Days":                   85,
	"Defaults":               191,
	"Define the default value when creating a new configuration.\nThe value here will not affect the existing configuration.": 192,
	"Delete":                        41,
	"Delete Date":                   83,
	"Delete Days":                   84,
	"Delete config \"%s\"":          48,
	"Delete proxy \"%s\"":           208,
	"Dial Timeout":                  94,
	"Direct Edit":                   205,
	"Disable":                       212,
	"Disable auto-start at boot":    113,
	"Disable proxy \"%s\"":          210,
	"Domains":                       206,
	"Download":                      219,
	"Download updates":              16,
	"Edit":                          30,
	"Edit Client - %s":              51,
	"Edit Proxy - %s":               120,
	"Empty":                         141,
	"Enable":                        203,
	"Encryption":                    142,
	"Enter Administration Password": 222,
	"Enter Password":                220,
	"Exit after login failure":      112,
	"Export All Configs to ZIP":     40,
	"FRP Manager":                   214,
	"FRP version: %s":               1,
	"Failure Count":                 160,
	"For FRP configuration documentation, please visit the FRP project page:": 20,
	"For comments or to report bugs, please visit the project page:":          19,
	"Group":                                  155,
	"Group Key":                              156,
	"HTTP File Server":                       202,
	"HTTP Password":                          145,
	"HTTP Proxy":                             88,
	"HTTP User":                              144,
	"Health Check":                           157,
	"Heart Beats":                            66,
	"Heartbeat":                              90,
	"Host Name":                              100,
	"Host Rewrite":                           146,
	"Idle Timeout":                           96,
	"Import Config":                          44,
	"Import Config from File":                27,
	"Import from Clipboard":                  38,
	"Import from File":                       36,
	"Import from URL":                        37,
	"Imported %d of %d configs.":             45,
	"Interval":                               91,
	"Invalid Input":                          224,
	"Keepalive":                              95,
	"Key Files":                              6,
	"Languages":                              187,
	"Latest":                                 166,
	"Level":                                  72,
	"Load Balance":                           154,
	"Local Address":                          126,
	"Local Directory":                        178,
	"Local Path":                             151,
	"Local Port":                             127,
	"Locations":                              134,
	"Log":                                    68,
	"Log File":                               70,
	"Log Files":                              7,
	"Log Level":                              198,
	"Log retention":                          199,
	"Manual Settings":                        43,
	"Master password":                        183,
	"Max Days":                               73,
	"Max Streams":                            97,
	"Multiplexer":                            135,
	"Mux Keepalive":                          109,
	"Name":                                   53,
	"New Client":                             50,
	"New Config":                             42,
	"New Configuration":                      26,
	"New Proxy":                              119,
	"New Version!":                           14,
	"New master password":                    195,
	"None":                                   59,
	"Not a number":                           12,
	"Number out of allowed range":            8,
	"OK":                                     23,
	"Off":                                    99,
	"On":                                     98,
	"Open Config":                            204,
	"Open File":                              31,
	"Open Log Folder":                        165,
	"Open Port":                              181,
	"Other Options":                          111,
	"Passive Port Range":                     213,
	"Password":                               77,
	"Password is set.":                       197,
	"Password mismatch":                      10,
	"Password removed.":                      194,
	"Please check and try again.":            11,
	"Please enter a number from %.f to %.f.": 225,
	"Please enter a number from %s to %s.":   226,
	"Please enter a number greater than %d.": 9,
	"Please enter a valid number.":           13,
	"Please enter the correct URL list.":     218,
	"Please select one of the provided options.": 229,
	"Plugin":                                 147,
	"Plugin Name":                            148,
	"Pool Count":                             89,
	"Port":                                   180,
	"Preferences":                            182,
	"Protocol":                               87,
	"Proxy Version":                          140,
	"Proxy already exists":                   163,
	"Quick Add":                              200,
	"Random":                                 121,
	"Re-enter password":                      196,
	"Ready":                                  217,
	"Relative":                               82,
	"Remote Address":                         173,
	"Remote Desktop":                         201,
	"Remote Port":                            128,
	"Rename automatically":                   216,
	"Role":                                   123,
	"Route User":                             136,
	"Running":                                168,
	"Scope":                                  63,
	"Secret":                                 61,
	"Secret Key":                             125,
	"Select Certificate File":                102,
	"Select Certificate Key File":            104,
	"Select Log File":                        71,
	"Select Trusted CA File":                 106,
	"Select Unix Path":                       150,
	"Select a folder for directory listing.": 152,
	"Select a local directory that the admin server will load resources from.": 79,
	"Select language":                        190,
	"Selection Required":                     228,
	"Server":                                 138,
	"Server Address":                         54,
	"Server Name":                            131,
	"Server Port":                            55,
	"Service":                                176,
	"Set Defaults":                           193,
	"Show in Folder":                         32,
	"Source Address":                         110,
	"Start":                                  175,
	"Starting":                               170,
	"Status":                                 172,
	"Stop":                                   177,
	"Stopped":                                169,
	"Stopping":                               171,
	"Strip Prefix":                           153,
	"Subdomain":                              132,
	"TCP Mux":                                108,
	"The config \"%s\" already removed.":     29,
	"The config name \"%s\" already exists.": 118,
	"The current display language is":        188,
	"The file \"%s\" is not a valid ZIP file.":      47,
	"The password is incorrect. Re-enter password.": 223,
	"The proxy name \"%s\" already exists.":         164,
	"The text does not match the required pattern.": 227,
	"There are currently no updates available.":     22,
	"Timeout":             93,
	"Token":               60,
	"Token Endpoint":      64,
	"Trusted CA":          105,
	"Type":                122,
	"Unix Path":           149,
	"Unknown":             167,
	"Use master password": 185,
	"User":                56,
	"Version: %s":         0,
	"Visitor":             124,
	"Work Conns":          67,
	"You can set a password to restrict access to this program.\nYou will be asked to enter it the next time you use this program.": 184,
	"You must enter an administration password to operate the %s.":                                                                  221,
	"You must restart program to apply the modification.":                                                                           189,
	"s": 92,
}

var en_USIndex = []uint32{ // 232 elements
	// Entry 0 - 1F
	0x00000000, 0x0000000f, 0x00000022, 0x00000032,
	0x0000003c, 0x00000050, 0x00000062, 0x0000006c,
	0x00000076, 0x00000092, 0x000000bc, 0x000000ce,
	0x000000ea, 0x000000f7, 0x00000114, 0x00000121,
	0x00000127, 0x00000138, 0x0000014d, 0x0000015f,
	0x0000019e, 0x000001e6, 0x0000021e, 0x00000248,
	0x0000024b, 0x00000252, 0x00000260, 0x00000272,
	0x0000028a, 0x000002a1, 0x000002c5, 0x000002ca,
	// Entry 20 - 3F
	0x000002d4, 0x000002e3, 0x000002f1, 0x000002f5,
	0x00000301, 0x00000312, 0x00000322, 0x00000338,
	0x00000348, 0x00000362, 0x00000369, 0x00000374,
	0x00000384, 0x00000392, 0x000003b3, 0x000003e8,
	0x00000412, 0x00000428, 0x0000045e, 0x00000469,
	0x0000047d, 0x00000483, 0x00000488, 0x00000497,
	0x000004a3, 0x000004a8, 0x000004ad, 0x000004b9,
	0x000004be, 0x000004c4, 0x000004cb, 0x000004d4,
	// Entry 40 - 5F
	0x000004da, 0x000004e9, 0x000004f8, 0x00000504,
	0x0000050f, 0x00000513, 0x00000554, 0x0000055d,
	0x0000056d, 0x00000573, 0x0000057c, 0x00000582,
	0x00000590, 0x0000059b, 0x000005a4, 0x000005ab,
	0x000005f4, 0x00000600, 0x00000609, 0x00000612,
	0x0000061e, 0x0000062a, 0x0000062f, 0x0000063a,
	0x00000643, 0x0000064e, 0x00000659, 0x00000663,
	0x0000066c, 0x0000066e, 0x00000676, 0x00000683,
	// Entry 60 - 7F
	0x0000068d, 0x0000069a, 0x000006a6, 0x000006a9,
	0x000006ad, 0x000006b7, 0x000006c3, 0x000006db,
	0x000006eb, 0x00000707, 0x00000712, 0x00000729,
	0x00000732, 0x0000073a, 0x00000748, 0x00000757,
	0x00000765, 0x0000077e, 0x00000799, 0x000007a0,
	0x000007af, 0x000007ee, 0x00000804, 0x0000082c,
	0x00000836, 0x00000849, 0x00000850, 0x00000855,
	0x0000085a, 0x00000862, 0x0000086d, 0x0000087b,
	// Entry 80 - 9F
	0x00000886, 0x00000892, 0x0000089f, 0x000008a9,
	0x000008b5, 0x000008bf, 0x000008ce, 0x000008d8,
	0x000008e4, 0x000008ef, 0x000008f6, 0x000008fd,
	0x00000907, 0x00000915, 0x0000091b, 0x00000926,
	0x00000932, 0x0000093c, 0x0000094a, 0x00000957,
	0x0000095e, 0x0000096a, 0x00000974, 0x00000985,
	0x00000990, 0x000009b7, 0x000009c4, 0x000009d1,
	0x000009d7, 0x000009e1, 0x000009ee, 0x000009f9,
	// Entry A0 - BF
	0x00000a07, 0x00000a15, 0x00000a24, 0x00000a50,
	0x00000a65, 0x00000a8c, 0x00000a9c, 0x00000aa3,
	0x00000aab, 0x00000ab3, 0x00000abb, 0x00000ac4,
	0x00000acd, 0x00000ad4, 0x00000ae3, 0x00000ae8,
	0x00000aee, 0x00000af6, 0x00000afb, 0x00000b0b,
	0x00000b0f, 0x00000b14, 0x00000b1e, 0x00000b2a,
	0x00000b3a, 0x00000bb7, 0x00000bcb, 0x00000bdb,
	0x00000be5, 0x00000c05, 0x00000c39, 0x00000c49,
	// Entry C0 - DF
	0x00000c52, 0x00000cc9, 0x00000cd6, 0x00000ce8,
	0x00000cfc, 0x00000d0e, 0x00000d1f, 0x00000d29,
	0x00000d37, 0x00000d41, 0x00000d50, 0x00000d61,
	0x00000d68, 0x00000d74, 0x00000d80, 0x00000d88,
	0x00000d9c, 0x00000db1, 0x00000de6, 0x00000dfc,
	0x00000e32, 0x00000e3a, 0x00000e4d, 0x00000e59,
	0x00000e84, 0x00000e99, 0x00000e9f, 0x00000ec2,
	0x00000ecb, 0x00000eda, 0x00000f1a, 0x00000f38,
	// Entry E0 - FF
	0x00000f66, 0x00000f74, 0x00000fa1, 0x00000fcc,
	0x00000ffa, 0x0000100d, 0x00001038, 0x00001051,
} // Size: 952 bytes

const en_USData string = "" + // Size: 4177 bytes
	"\x02Version: %[1]s\x02FRP version: %[1]s\x02Built on: %[1]s\x02All Files" +
	"\x02Configuration Files\x02Certificate Files\x02Key Files\x02Log Files" +
	"\x02Number out of allowed range\x02Please enter a number greater than %[" +
	"1]d.\x02Password mismatch\x02Please check and try again.\x02Not a number" +
	"\x02Please enter a valid number.\x02New Version!\x02About\x02Download up" +
	"dates\x02Checking for updates\x02Check for updates\x02For comments or to" +
	" report bugs, please visit the project page:\x02For FRP configuration do" +
	"cumentation, please visit the FRP project page:\x02An error occurred whi" +
	"le checking for a software update.\x02There are currently no updates ava" +
	"ilable.\x02OK\x02Cancel\x02Configuration\x02New Configuration\x02Import " +
	"Config from File\x02Config already removed\x02The config \x22%[1]s\x22 a" +
	"lready removed.\x02Edit\x02Open File\x02Show in Folder\x02Create a Copy" +
	"\x02All\x02Common Only\x02Import from File\x02Import from URL\x02Import " +
	"from Clipboard\x02Copy Share Link\x02Export All Configs to ZIP\x02Delete" +
	"\x02New Config\x02Manual Settings\x02Import Config\x02Imported %[1]d of " +
	"%[2]d configs.\x02Another config already exists with the name \x22%[1]s" +
	"\x22.\x02The file \x22%[1]s\x22 is not a valid ZIP file.\x02Delete confi" +
	"g \x22%[1]s\x22\x02Are you sure you would like to delete config \x22%[1]" +
	"s\x22?\x02New Client\x02Edit Client - %[1]s\x02Basic\x02Name\x02Server A" +
	"ddress\x02Server Port\x02User\x02Auth\x02Auth Method\x02None\x02Token" +
	"\x02Secret\x02Audience\x02Scope\x02Token Endpoint\x02Authentication\x02H" +
	"eart Beats\x02Work Conns\x02Log\x02* Leave blank to record no log and de" +
	"lete the original log file.\x02Log File\x02Select Log File\x02Level\x02M" +
	"ax Days\x02Admin\x02Admin Address\x02Admin Port\x02Password\x02Assets" +
	"\x02Select a local directory that the admin server will load resources f" +
	"rom.\x02Auto Delete\x02Absolute\x02Relative\x02Delete Date\x02Delete Day" +
	"s\x02Days\x02Connection\x02Protocol\x02HTTP Proxy\x02Pool Count\x02Heart" +
	"beat\x02Interval\x02s\x02Timeout\x02Dial Timeout\x02Keepalive\x02Idle Ti" +
	"meout\x02Max Streams\x02On\x02Off\x02Host Name\x02Certificate\x02Select " +
	"Certificate File\x02Certificate Key\x02Select Certificate Key File\x02Tr" +
	"usted CA\x02Select Trusted CA File\x02Advanced\x02TCP Mux\x02Mux Keepali" +
	"ve\x02Source Address\x02Other Options\x02Exit after login failure\x02Dis" +
	"able auto-start at boot\x02Custom\x02Custom Options\x02* Refer to the [c" +
	"ommon] section of the FRP configuration file.\x02Config already exists" +
	"\x02The config name \x22%[1]s\x22 already exists.\x02New Proxy\x02Edit P" +
	"roxy - %[1]s\x02Random\x02Type\x02Role\x02Visitor\x02Secret Key\x02Local" +
	" Address\x02Local Port\x02Remote Port\x02Bind Address\x02Bind Port\x02Se" +
	"rver Name\x02Subdomain\x02Custom Domains\x02Locations\x02Multiplexer\x02" +
	"Route User\x02Client\x02Server\x02Bandwidth\x02Proxy Version\x02Empty" +
	"\x02Encryption\x02Compression\x02HTTP User\x02HTTP Password\x02Host Rewr" +
	"ite\x02Plugin\x02Plugin Name\x02Unix Path\x02Select Unix Path\x02Local P" +
	"ath\x02Select a folder for directory listing.\x02Strip Prefix\x02Load Ba" +
	"lance\x02Group\x02Group Key\x02Health Check\x02Check Type\x02Check Timeo" +
	"ut\x02Failure Count\x02Check Interval\x02* Refer to the parameters suppo" +
	"rted by FRP.\x02Proxy already exists\x02The proxy name \x22%[1]s\x22 alr" +
	"eady exists.\x02Open Log Folder\x02Latest\x02Unknown\x02Running\x02Stopp" +
	"ed\x02Starting\x02Stopping\x02Status\x02Remote Address\x02Copy\x02Start" +
	"\x02Service\x02Stop\x02Local Directory\x02Add\x02Port\x02Open Port\x02Pr" +
	"eferences\x02Master password\x02You can set a password to restrict acces" +
	"s to this program.\x0aYou will be asked to enter it the next time you us" +
	"e this program.\x02Use master password\x02Change Password\x02Languages" +
	"\x02The current display language is\x02You must restart program to apply" +
	" the modification.\x02Select language\x02Defaults\x02Define the default " +
	"value when creating a new configuration.\x0aThe value here will not affe" +
	"ct the existing configuration.\x02Set Defaults\x02Password removed.\x02N" +
	"ew master password\x02Re-enter password\x02Password is set.\x02Log Level" +
	"\x02Log retention\x02Quick Add\x02Remote Desktop\x02HTTP File Server\x02" +
	"Enable\x02Open Config\x02Direct Edit\x02Domains\x02Copy Access Address" +
	"\x02Delete proxy \x22%[1]s\x22\x02Are you sure you would like to delete " +
	"proxy \x22%[1]s\x22?\x02Disable proxy \x22%[1]s\x22\x02Are you sure you " +
	"would like to disable proxy \x22%[1]s\x22?\x02Disable\x02Passive Port Ra" +
	"nge\x02FRP Manager\x02* Support batch import, one link per line.\x02Rena" +
	"me automatically\x02Ready\x02Please enter the correct URL list.\x02Downl" +
	"oad\x02Enter Password\x02You must enter an administration password to op" +
	"erate the %[1]s.\x02Enter Administration Password\x02The password is inc" +
	"orrect. Re-enter password.\x02Invalid Input\x02Please enter a number fro" +
	"m %.[1]f to %.[2]f.\x02Please enter a number from %[1]s to %[2]s.\x02The" +
	" text does not match the required pattern.\x02Selection Required\x02Plea" +
	"se select one of the provided options.\x02A selection is required."

var zh_CNIndex = []uint32{ // 232 elements
	// Entry 0 - 1F
	0x00000000, 0x0000000f, 0x00000022, 0x00000037,
	0x00000044, 0x00000051, 0x0000005e, 0x0000006b,
	0x00000078, 0x00000091, 0x000000ba, 0x000000ca,
	0x000000e0, 0x000000ed, 0x0000010f, 0x0000011f,
	0x00000126, 0x00000133, 0x00000146, 0x00000153,
	0x00000190, 0x000001ce, 0x000001ed, 0x0000020c,
	0x00000213, 0x0000021a, 0x00000221, 0x0000022e,
	0x00000244, 0x00000254, 0x00000275, 0x0000027c,
	// Entry 20 - 3F
	0x00000289, 0x0000029f, 0x000002ac, 0x000002b3,
	0x000002c3, 0x000002d3, 0x000002e2, 0x000002f5,
	0x00000308, 0x0000032b, 0x00000332, 0x0000033f,
	0x0000034c, 0x00000359, 0x0000038c, 0x000003bc,
	0x000003ea, 0x00000402, 0x00000441, 0x00000451,
	0x00000469, 0x00000470, 0x00000477, 0x00000487,
	0x00000497, 0x000004a1, 0x000004a8, 0x000004b5,
	0x000004b9, 0x000004c0, 0x000004c7, 0x000004d1,
	// Entry 40 - 5F
	0x000004db, 0x000004e8, 0x000004ef, 0x000004fc,
	0x00000509, 0x00000510, 0x0000054f, 0x0000055c,
	0x0000056f, 0x00000576, 0x00000583, 0x0000058a,
	0x00000597, 0x000005a4, 0x000005ab, 0x000005b8,
	0x000005ec, 0x000005f9, 0x00000600, 0x00000607,
	0x00000614, 0x00000621, 0x00000625, 0x0000062c,
	0x00000633, 0x0000063f, 0x0000064f, 0x00000656,
	0x0000065d, 0x00000661, 0x00000668, 0x00000675,
	// Entry 60 - 7F
	0x00000682, 0x0000068f, 0x0000069f, 0x000006a6,
	0x000006ad, 0x000006ba, 0x000006c7, 0x000006da,
	0x000006e7, 0x00000700, 0x00000710, 0x00000729,
	0x00000730, 0x0000073d, 0x0000074d, 0x0000075d,
	0x0000076a, 0x00000786, 0x0000079c, 0x000007a6,
	0x000007b6, 0x000007e6, 0x000007f6, 0x00000817,
	0x00000824, 0x00000839, 0x00000846, 0x0000084d,
	0x00000854, 0x0000085e, 0x00000865, 0x00000872,
	// Entry 80 - 9F
	0x0000087f, 0x0000088c, 0x00000899, 0x000008a6,
	0x000008b3, 0x000008bd, 0x000008cd, 0x000008d8,
	0x000008e2, 0x000008ef, 0x000008f9, 0x00000903,
	0x00000910, 0x0000091d, 0x00000921, 0x0000092e,
	0x0000093b, 0x00000947, 0x00000953, 0x0000095f,
	0x00000966, 0x00000973, 0x0000097f, 0x00000992,
	0x0000099f, 0x000009cd, 0x000009da, 0x000009e7,
	0x000009f4, 0x00000a01, 0x00000a0e, 0x00000a1b,
	// Entry A0 - BF
	0x00000a28, 0x00000a35, 0x00000a42, 0x00000a62,
	0x00000a72, 0x00000a93, 0x00000aa9, 0x00000ab0,
	0x00000ab7, 0x00000ac4, 0x00000ace, 0x00000adb,
	0x00000ae8, 0x00000aef, 0x00000afc, 0x00000b03,
	0x00000b0a, 0x00000b11, 0x00000b18, 0x00000b25,
	0x00000b2c, 0x00000b33, 0x00000b40, 0x00000b47,
	0x00000b51, 0x00000bbf, 0x00000bcf, 0x00000bdc,
	0x00000be3, 0x00000bf9, 0x00000c2a, 0x00000c37,
	// Entry C0 - DF
	0x00000c41, 0x00000c91, 0x00000ca1, 0x00000cb4,
	0x00000cc1, 0x00000cce, 0x00000ce1, 0x00000cee,
	0x00000cfb, 0x00000d08, 0x00000d15, 0x00000d27,
	0x00000d2e, 0x00000d41, 0x00000d4e, 0x00000d55,
	0x00000d68, 0x00000d80, 0x00000da7, 0x00000dbf,
	0x00000de6, 0x00000ded, 0x00000e00, 0x00000e0e,
	0x00000e3b, 0x00000e4b, 0x00000e58, 0x00000e79,
	0x00000e80, 0x00000e8d, 0x00000ebb, 0x00000ece,
	// Entry E0 - FF
	0x00000ef0, 0x00000efd, 0x00000f2f, 0x00000f5f,
	0x00000f84, 0x00000f8e, 0x00000fad, 0x00000fbd,
} // Size: 952 bytes

const zh_CNData string = "" + // Size: 4029 bytes
	"\x02版本：%[1]s\x02FRP 版本：%[1]s\x02构建日期：%[1]s\x02所有文件\x02配置文件\x02证书文件\x02密钥" +
	"文件\x02日志文件\x02数值超出允许范围\x02请输入一个大于 %[1]d 的数字。\x02密码不匹配\x02请检查并重试。\x02不是" +
	"数字\x02请输入一个有效的数字。\x02发现更新！\x02关于\x02下载更新\x02正在检查更新\x02检查更新\x02如有任何意见或报" +
	"告错误，请访问项目地址：\x02了解 FRP 软件配置文档，请访问 FRP 项目地址：\x02检查更新时出现错误。\x02当前没有可用的更新" +
	"。\x02确定\x02取消\x02配置\x02新建配置\x02从文件导入配置\x02配置已删除\x02配置名「%[1]s」已删除。\x02编" +
	"辑\x02打开文件\x02在文件夹中显示\x02创建副本\x02全部\x02仅通用配置\x02从文件导入\x02从 URL 导入\x02从剪" +
	"贴板导入\x02复制分享链接\x02导出所有配置 (ZIP 压缩包)\x02删除\x02新建配置\x02手动设置\x02导入配置\x02导入" +
	"了 %[2]d 个配置文件中的 %[1]d 个。\x02另一个同名的配置「%[1]s」已存在。\x02文件 \x22%[1]s\x22 不是" +
	"有效的压缩文件。\x02删除配置「%[1]s」\x02确定要删除配置「%[1]s」吗？此操作无法撤销。\x02新建客户端\x02编辑客户端 " +
	"- %[1]s\x02基本\x02名称\x02服务器地址\x02服务器端口\x02用户名\x02认证\x02认证方式\x02无\x02令牌" +
	"\x02密钥\x02接收者\x02作用域\x02令牌地址\x02鉴权\x02心跳消息\x02工作连接\x02日志\x02* 留空则不记录日志，且" +
	"删除原来的日志文件。\x02日志文件\x02选择日志文件\x02级别\x02最大天数\x02管理\x02管理地址\x02管理端口\x02密码" +
	"\x02静态资源\x02选择管理服务器使用的静态资源目录。\x02自动删除\x02绝对\x02相对\x02删除日期\x02删除天数\x02天" +
	"\x02连接\x02协议\x02HTTP 代理\x02连接池数量\x02心跳\x02间隔\x02秒\x02超时\x02连接超时\x02保活周期" +
	"\x02闲置超时\x02最大流数量\x02开启\x02关闭\x02主机名称\x02证书文件\x02选择证书文件\x02密钥文件\x02选择证书密" +
	"钥文件\x02受信任证书\x02选择受信任的证书\x02高级\x02多路复用\x02复用器心跳\x02使用源地址\x02其他选项\x02初次" +
	"登录失败后退出\x02禁用开机自启动\x02自定义\x02自定义参数\x02* 参考 FRP 配置文件的 [common] 部分。\x02配" +
	"置已存在\x02配置名「%[1]s」已存在。\x02新建代理\x02编辑代理 - %[1]s\x02随机名称\x02类型\x02角色\x02" +
	"访问者\x02私钥\x02本地地址\x02本地端口\x02远程端口\x02绑定地址\x02绑定端口\x02服务名称\x02子域名\x02自定" +
	"义域名\x02URL 路由\x02复用器\x02路由用户\x02客户端\x02服务端\x02带宽限流\x02代理版本\x02空\x02加密传" +
	"输\x02压缩传输\x02HTTP 用户\x02HTTP 密码\x02Host 替换\x02插件\x02插件名称\x02Unix 路径" +
	"\x02选择 Unix 路径\x02本地路径\x02选择需要显示目录列表的文件夹。\x02移除前缀\x02负载均衡\x02分组名称\x02分组密" +
	"钥\x02健康检查\x02检查类型\x02检查超时\x02错误次数\x02检查周期\x02* 参考 FRP 支持的参数。\x02代理已存在" +
	"\x02代理名「%[1]s」已存在。\x02打开日志文件夹\x02最新\x02未知\x02正在运行\x02已停止\x02正在启动\x02正在停止" +
	"\x02状态\x02远程地址\x02复制\x02启动\x02服务\x02停止\x02本地目录\x02添加\x02端口\x02打开端口\x02选项" +
	"\x02主密码\x02您可以设置密码来限制访问此程序。\x0a在下次使用此程序时，您将被要求输入密码。\x02使用主密码\x02修改密码\x02" +
	"语言\x02目前的显示语言\x02您必须重新启动程序才能应用修改。\x02选择语言\x02默认值\x02定义新建配置时的默认值。\x0a此处" +
	"的值不会影响现有的配置。\x02设置默认值\x02密码已删除。\x02新主密码\x02确认密码\x02密码已设定。\x02日志级别\x02日" +
	"志保留\x02快速添加\x02远程桌面\x02HTTP 文件服务\x02启用\x02打开配置文件\x02直接编辑\x02域名\x02复制访问" +
	"地址\x02删除代理「%[1]s」\x02确定要删除代理「%[1]s」吗？\x02禁用代理「%[1]s」\x02确定要禁用代理「%[1]s」" +
	"吗？\x02禁用\x02被动端口范围\x02FRP 管理器\x02* 支持批量导入，每行一个链接。\x02自动重命名\x02准备就绪\x02" +
	"请输入正确的 URL 列表。\x02下载\x02输入密码\x02您必须输入管理密码来使用 %[1]s。\x02输入管理密码\x02密码错误。" +
	"请重新输入。\x02输入无效\x02请输入一个从 %.[1]f 到 %.[2]f 的数字。\x02请输入一个从 %[1]s 到 %[2]s " +
	"的数字。\x02文本与要求的模式不匹配。\x02必填项\x02请选择其中一个选项。\x02需要选择。"

var zh_TWIndex = []uint32{ // 232 elements
	// Entry 0 - 1F
	0x00000000, 0x0000000f, 0x00000022, 0x00000037,
	0x00000044, 0x00000051, 0x0000005e, 0x0000006b,
	0x00000078, 0x00000091, 0x000000ba, 0x000000ca,
	0x000000e0, 0x000000ed, 0x0000010f, 0x0000011f,
	0x00000126, 0x00000133, 0x00000146, 0x00000153,
	0x00000190, 0x000001ce, 0x000001ed, 0x0000020c,
	0x00000213, 0x0000021a, 0x00000221, 0x0000022e,
	0x00000244, 0x00000254, 0x00000275, 0x0000027c,
	// Entry 20 - 3F
	0x00000289, 0x0000029f, 0x000002ac, 0x000002b3,
	0x000002c3, 0x000002d3, 0x000002e2, 0x000002f5,
	0x00000308, 0x0000032b, 0x00000332, 0x0000033f,
	0x0000034c, 0x00000359, 0x0000038c, 0x000003bc,
	0x000003ea, 0x00000402, 0x00000441, 0x00000451,
	0x00000469, 0x00000470, 0x00000477, 0x00000487,
	0x00000497, 0x000004a1, 0x000004a8, 0x000004b5,
	0x000004b9, 0x000004c0, 0x000004c7, 0x000004d1,
	// Entry 40 - 5F
	0x000004db, 0x000004e8, 0x000004ef, 0x000004fc,
	0x00000509, 0x00000510, 0x0000054f, 0x0000055c,
	0x0000056f, 0x00000576, 0x00000583, 0x0000058a,
	0x00000597, 0x000005a4, 0x000005ab, 0x000005b8,
	0x000005ec, 0x000005f9, 0x00000600, 0x00000607,
	0x00000614, 0x00000621, 0x00000625, 0x0000062c,
	0x00000633, 0x0000063f, 0x0000064f, 0x00000656,
	0x0000065d, 0x00000661, 0x00000668, 0x00000675,
	// Entry 60 - 7F
	0x00000682, 0x0000068f, 0x0000069f, 0x000006a6,
	0x000006ad, 0x000006ba, 0x000006c7, 0x000006da,
	0x000006e7, 0x00000700, 0x00000710, 0x00000729,
	0x00000730, 0x0000073d, 0x0000074d, 0x0000075d,
	0x0000076a, 0x00000786, 0x0000079c, 0x000007a6,
	0x000007b6, 0x000007e6, 0x000007f6, 0x00000817,
	0x00000824, 0x00000839, 0x00000846, 0x0000084d,
	0x00000854, 0x0000085e, 0x00000865, 0x00000872,
	// Entry 80 - 9F
	0x0000087f, 0x0000088c, 0x00000899, 0x000008a6,
	0x000008b3, 0x000008bd, 0x000008cd, 0x000008d8,
	0x000008e2, 0x000008ef, 0x000008f9, 0x00000903,
	0x00000910, 0x0000091d, 0x00000921, 0x0000092e,
	0x0000093b, 0x00000947, 0x00000953, 0x0000095f,
	0x00000966, 0x00000973, 0x0000097f, 0x00000992,
	0x0000099f, 0x000009cd, 0x000009da, 0x000009e7,
	0x000009f4, 0x00000a01, 0x00000a0e, 0x00000a1b,
	// Entry A0 - BF
	0x00000a28, 0x00000a35, 0x00000a42, 0x00000a62,
	0x00000a72, 0x00000a93, 0x00000aa9, 0x00000ab0,
	0x00000ab7, 0x00000ac4, 0x00000ace, 0x00000adb,
	0x00000ae8, 0x00000aef, 0x00000afc, 0x00000b03,
	0x00000b0a, 0x00000b11, 0x00000b18, 0x00000b25,
	0x00000b2c, 0x00000b33, 0x00000b40, 0x00000b47,
	0x00000b51, 0x00000bbf, 0x00000bcf, 0x00000bdc,
	0x00000be3, 0x00000bf9, 0x00000c2a, 0x00000c37,
	// Entry C0 - DF
	0x00000c41, 0x00000c91, 0x00000ca1, 0x00000cb4,
	0x00000cc1, 0x00000cce, 0x00000ce1, 0x00000cee,
	0x00000cfb, 0x00000d08, 0x00000d15, 0x00000d27,
	0x00000d2e, 0x00000d41, 0x00000d4e, 0x00000d55,
	0x00000d68, 0x00000d80, 0x00000da7, 0x00000dbf,
	0x00000de6, 0x00000ded, 0x00000e00, 0x00000e0e,
	0x00000e3b, 0x00000e4b, 0x00000e58, 0x00000e79,
	0x00000e80, 0x00000e8d, 0x00000ebb, 0x00000ece,
	// Entry E0 - FF
	0x00000ef0, 0x00000efd, 0x00000f2f, 0x00000f5f,
	0x00000f84, 0x00000f8e, 0x00000fad, 0x00000fbd,
} // Size: 952 bytes

const zh_TWData string = "" + // Size: 4029 bytes
	"\x02版本：%[1]s\x02FRP 版本：%[1]s\x02構建日期：%[1]s\x02所有文件\x02配置文件\x02證書文件\x02密鑰" +
	"文件\x02日誌文件\x02數值超出允許範圍\x02請輸入一個大於 %[1]d 的數字。\x02密碼不匹配\x02請檢查並重試。\x02不是" +
	"數字\x02請輸入一個有效的數字。\x02發現更新！\x02關於\x02下載更新\x02正在檢查更新\x02檢查更新\x02如有任何意見或報" +
	"告錯誤，請訪問項目地址：\x02了解 FRP 軟件配置文檔，請訪問 FRP 項目地址：\x02檢查更新時出現錯誤。\x02當前沒有可用的更新" +
	"。\x02確定\x02取消\x02配置\x02新建配置\x02從文件導入配置\x02配置已刪除\x02配置名「%[1]s」已刪除。\x02編" +
	"輯\x02打開文件\x02在文件夾中顯示\x02創建副本\x02全部\x02僅通用配置\x02從文件導入\x02從 URL 導入\x02從剪" +
	"貼板導入\x02復制分享鏈接\x02導出所有配置 (ZIP 壓縮包)\x02刪除\x02新建配置\x02手動設置\x02導入配置\x02導入" +
	"了 %[2]d 個配置文件中的 %[1]d 個。\x02另一個同名的配置「%[1]s」已存在。\x02文件 \x22%[1]s\x22 不是" +
	"有效的壓縮文件。\x02刪除配置「%[1]s」\x02確定要刪除配置「%[1]s」嗎？此操作無法撤銷。\x02新建客戶端\x02編輯客戶端 " +
	"- %[1]s\x02基本\x02名稱\x02服務器地址\x02服務器端口\x02用戶名\x02認證\x02認證方式\x02無\x02令牌" +
	"\x02密鑰\x02接收者\x02作用域\x02令牌地址\x02鑑權\x02心跳消息\x02工作連接\x02日誌\x02* 留空則不記錄日誌，且" +
	"刪除原來的日誌文件。\x02日誌文件\x02選擇日誌文件\x02級別\x02最大天數\x02管理\x02管理地址\x02管理端口\x02密碼" +
	"\x02靜態資源\x02選擇管理服務器使用的靜態資源目錄。\x02自動刪除\x02絕對\x02相對\x02刪除日期\x02刪除天數\x02天" +
	"\x02連接\x02協議\x02HTTP 代理\x02連接池數量\x02心跳\x02間隔\x02秒\x02超時\x02連接超時\x02保活週期" +
	"\x02閒置超時\x02最大流數量\x02開啟\x02關閉\x02主機名稱\x02證書文件\x02選擇證書文件\x02密鑰文件\x02選擇證書密" +
	"鑰文件\x02受信任證書\x02選擇受信任的證書\x02高級\x02多路復用\x02復用器心跳\x02使用源地址\x02其他選項\x02初次" +
	"登錄失敗後退出\x02禁用開機自啟動\x02自定義\x02自定義參數\x02* 參考 FRP 配置文件的 [common] 部分。\x02配" +
	"置已存在\x02配置名「%[1]s」已存在。\x02新建代理\x02編輯代理 - %[1]s\x02隨機名稱\x02類型\x02角色\x02" +
	"訪問者\x02私鑰\x02本地地址\x02本地端口\x02遠程端口\x02綁定地址\x02綁定端口\x02服務名稱\x02子域名\x02自定" +
	"義域名\x02URL 路由\x02復用器\x02路由用戶\x02客戶端\x02服務端\x02帶寬限流\x02代理版本\x02空\x02加密傳" +
	"輸\x02壓縮傳輸\x02HTTP 用戶\x02HTTP 密碼\x02Host 替換\x02插件\x02插件名稱\x02Unix 路徑" +
	"\x02選擇 Unix 路徑\x02本地路徑\x02選擇需要顯示目錄列表的文件夾。\x02移除前綴\x02負載均衡\x02分組名稱\x02分組密" +
	"鑰\x02健康檢查\x02檢查類型\x02檢查超時\x02錯誤次數\x02檢查週期\x02* 參考 FRP 支持的參數。\x02代理已存在" +
	"\x02代理名「%[1]s」已存在。\x02打開日誌文件夾\x02最新\x02未知\x02正在運行\x02已停止\x02正在啟動\x02正在停止" +
	"\x02狀態\x02遠程地址\x02複製\x02啟動\x02服務\x02停止\x02本地目錄\x02添加\x02端口\x02打開端口\x02選項" +
	"\x02主密碼\x02您可以設置密碼來限制訪問此程式。\x0a在下次使用此程式時，您將被要求輸入密碼。\x02使用主密碼\x02修改密碼\x02" +
	"語言\x02目前的顯示語言\x02您必須重新啟動程式才能應用修改。\x02選擇語言\x02默認值\x02定義新建配置時的默認值。\x0a此處" +
	"的值不會影響現有的配置。\x02設置默認值\x02密碼已刪除。\x02新主密碼\x02確認密碼\x02密碼已設定。\x02日誌級別\x02日" +
	"誌保留\x02快速添加\x02遠程桌面\x02HTTP 文件服務\x02啟用\x02打開配置文件\x02直接編輯\x02域名\x02複製訪問" +
	"地址\x02刪除代理「%[1]s」\x02確定要刪除代理「%[1]s」嗎？\x02禁用代理「%[1]s」\x02確定要禁用代理「%[1]s」" +
	"嗎？\x02禁用\x02被動端口範圍\x02FRP 管理器\x02* 支持批量導入，每行一個鏈接。\x02自動重命名\x02準備就緒\x02" +
	"請輸入正確的 URL 列表。\x02下載\x02輸入密碼\x02您必須輸入管理密碼來使用 %[1]s。\x02輸入管理密碼\x02密碼錯誤。" +
	"請重新輸入。\x02輸入無效\x02請輸入一個從 %.[1]f 到 %.[2]f 的數字。\x02請輸入一個從 %[1]s 到 %[2]s " +
	"的數字。\x02文本與要求的模式不匹配。\x02必填項\x02請選擇其中一個選項。\x02需要選擇。"

	// Total table size 34683 bytes (33KiB); checksum: F8713DA1
